sudo: false
language: node_js
node_js:
  - "6"

addons:
  apt:
    packages:
    - xvfb

before_install:
  - "npm install -g testling"
  - "npm install -g browserify"
  - "export DISPLAY=:99.0"
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

